name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: 'Set Java 11 with Maven cache'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Check supported distributions at https://github.com/marketplace/actions/setup-java-jdk
          java-version: '11'
          cache: 'maven'
      - name: Autograding
        uses: education/autograding@v1
